config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :cards
  root 'pages#home'
  get "bootstrap" => "pages#bootstrap"

end

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :user
	belongs_to :project
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :cards, through: :users
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cards
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :projects_exist, only: [:new]
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = current_user.cards.build
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = current_user.cards.build(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

   def correct_user
      @card = current_user.cards.find_by(id: params[:id])
      redirect_to cards_path, notice: "Not authorized to edit this card" if @card.nil?
    end

   def projects_exist
      @project = Project.first
      redirect_to projects_path, notice: "Create project first" if @project.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:description, :project_id, :duedate)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	def bootstrap
  	end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  # update to destroy cards with the project or sth
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

   def correct_user
      @project = current_user.projects.find_by(id: params[:id])
      redirect_to projects_path, notice: "Not authorized to edit this project" if @project.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :"describe the next steps" %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :"describe the next steps" %>
    <%= f.collection_select :project_id, Project.all, :id, :name, {}, {:class=>'form-control'}  %>
  </div>

  <div class="row">
    <div class="col-sm-3">
      <%= f.label :"select due date" %><br />
      <div class="input-group date datepicker">
        <%= f.text_field :duedate, class: "form-control", value: Date.today.strftime('%d/%m/%Y')%>   
        <span class="input-group-addon" id="btn" style="cursor:pointer;">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>      
      </div>
    </div>
  </div>


  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="masonary-cards transitions-enabled">
  <% @cards.each do |card| %>
    <% if Date.today >= card.duedate %>
      <div class = "box panel panel-delayed">
      <div class = "panel-box-delayed"><%= card.description %></div>
    <% else %>
      <div class = "box panel panel-ontime">
      <div class = "panel-box-ontime"><%= card.description %></div> 
    <% end %>
        <div class = "panel-body">
          <strong><%= card.user.email if card.user %></strong><br/>
          <%= card.project_id %><br/>
          <%= card.duedate %>
          <div class = "action">
            <%= link_to 'Show', card_path(card) %>
            <% if card.user == current_user %>
              <%= link_to 'Edit', edit_card_path(card) %>
              <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>
<% if @card.user == current_user %>
	<%= link_to 'Edit', edit_card_path(@card) %> |
<% end %>
<%= link_to 'Back', cards_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "@Cards", root_path, class: "navbar-brand" %>
    </div>

    <%= form_for(:user, :url => session_path(:user)) do |f| %>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="navbar-form navbar-right">
           <% if user_signed_in? %>
            <%= link_to 'New Card', new_card_path, class: "btn btn-success" %>
            <%= link_to 'New Project', new_project_path, class: "btn btn-success" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "btn btn-primary" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-default" %>
          <% else %>
            <div class="form-group">
              <%= f.email_field :email, class: "form-control", :autofocus => true, placeholder: 'Email' %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, class: "form-control", :autofocus =>true, placeholder: 'Password' %>
            </div>
            <div class="form-group">
              <%= f.submit "Sign in", class: "btn btn-success" %>
            </div>
            </div>
          <% end %>
        </ul>
      <% end %>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post It</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
  		   <%= content_tag(:div, msg, class: "alert alert-info alert-#{name}") %>
		<% end %>
	    <%= yield %>
	</div>
	
</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
     <h1>Welcome to my app!</h1>
     <% if user_signed_in? %>
          # do something <br>
     <% else %>
       <p>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>
  <%= link_to "Bootstrap", bootstrap_path %>  
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :"Project title" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :"short description" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_index_cards.html.erb
<div class="masonary-cards transitions-enabled">
  <% @cards.each do |card| %>
    <% if Date.today >= card.duedate %>
      <div class = "box panel panel-delayed">
      <div class = "panel-box-delayed"><%= card.description %></div>
    <% else %>
      <div class = "box panel panel-ontime">
      <div class = "panel-box-ontime"><%= card.description %></div> 
    <% end %>
        <div class = "panel-body">
          <strong><%= card.user.email if card.user %></strong><br/>
          <%= card.project_id %><br/>
          <%= card.duedate %>
          <div class = "action">
            <%= link_to 'Show', card_path(card) %>
            <% if card.user == current_user %>
              <%= link_to 'Edit', edit_card_path(card) %>
              <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th>Description</th>
      <th>Cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.user.email if project.user %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <% if project.user == current_user %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
<%= link_to 'New Project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project Description:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user.email %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<% if @project.user == current_user %>
	<%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>

<p>
  <strong>Cards:</strong>
</p>

<% @cards = Card.all %>
<%= render 'index_cards.html.erb' %>